### ISSUE TITLE
TRied to install all colors but only blue is installed

### ISSUE THREAD

**Issue by pjhalsli** [yeyushengfan258/Lyra-icon-theme#3]
redad in another issue that there were included an makepkg but I can't find it.

I tried installing yeallow , purple and green and blue is the only color installed

on a side note is there a way to get the cursor bigger I have a 4k display and the cursors are almost invisible. Tried  x2 but same result  blue and same sixe

edit :
sorry It was the cursors I was unable to make bigger . the icon-theme works great. Nice job.
also want to thank @KiranWells for the pkgbuild -hihly appreciated.  Still haven't solved how to make the cursor bigger tho

**Comment by yeyushengfan258** [comment]
The size can be adjusted in the cursor setting.

**Comment by pjhalsli** [comment]
what cursor setings are you talking about? I use lxappearance to set my cursors and there's no option to make the cursor bigger 

I go into src and ,/build.sh but the size is the same - and there's no color but 
blue
ps is there a pkgbuild for this? I saw it mentioned in another issue?

**Comment by yeyushengfan258** [comment]
Is it not in the system's own settings?
